packages:
  - "."

allowBuilds:
  esbuild: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@4.20260714.0
  - wrangler@4.112.0
onlyBuiltDependencies:
  - esbuild
  - workerd
